# Generated by Django 5.1.6 on 2025-02-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifyuser',
            name='id',
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='spotify_id',
            field=models.CharField(default='notanid', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
