# Generated by Django 5.1.6 on 2025-02-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_spotifyuser_id_spotifyuser_spotify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuser',
            name='spotify_id',
            field=models.CharField(default='admin', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
