# Generated by Django 5.1.6 on 2025-02-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_spotifyuser_spotify_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='spotifyuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='spotifyuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
