# Generated by Django 5.1.6 on 2025-02-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_spotifyuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
