# Generated by Django 5.1.6 on 2025-02-17 16:20

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_spotifyuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='spotifyuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='spotifyuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='spotifyuser',
            name='spotify_id',
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
